FROM --platform=linux/amd64 docker.io/node:22-alpine3.21

ENV NODE_OPTIONS="--max-old-space-size=2096"

WORKDIR /usr/src/app

COPY package.json .

COPY pnpm-lock.yaml .

RUN npm install -g pnpm@10

RUN pnpm install

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["pnpm", "run", "start"]
